// GENERATED by audit script (2026-08-21) — smoke test: every component example
// page registered in example/lib/main.dart must render without throwing.
// Regenerate with the same script after changing main.dart's _componentPages.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:example/l10n/app_localizations.dart';
import 'package:example/pages/label_page.dart';
import 'package:example/pages/input_page.dart';
import 'package:example/pages/button_page.dart';
import 'package:example/pages/check_box_page.dart';
import 'package:example/pages/radio_button_page.dart';
import 'package:example/pages/combo_box_page.dart';
import 'package:example/pages/link_label_page.dart';
import 'package:example/pages/masked_text_box_page.dart';
import 'package:example/pages/numeric_up_down_page.dart';
import 'package:example/pages/domain_up_down_page.dart';
import 'package:example/pages/field_row_page.dart';
import 'package:example/pages/icon_btn_page.dart';
import 'package:example/pages/selectable_card_page.dart';
import 'package:example/pages/surface_page.dart';
import 'package:example/pages/checked_list_box_page.dart';
import 'package:example/pages/list_view_page.dart';
import 'package:example/pages/list_item_page.dart';
import 'package:example/pages/tree_view_page.dart';
import 'package:example/pages/data_grid_view_page.dart';
import 'package:example/pages/property_grid_page.dart';
import 'package:example/pages/menu_strip_page.dart';
import 'package:example/pages/tool_strip_page.dart';
import 'package:example/pages/toolbar_button_page.dart';
import 'package:example/pages/context_menu_strip_page.dart';
import 'package:example/pages/status_strip_page.dart';
import 'package:example/pages/date_time_picker_page.dart';
import 'package:example/pages/month_calendar_page.dart';
import 'package:example/pages/color_dialog_page.dart';
import 'package:example/pages/dialog_box_page.dart';
import 'package:example/pages/theme_designer_page.dart';
import 'package:example/pages/binding_navigator_page.dart';
import 'package:example/pages/scroll_bar_page.dart';
import 'package:example/pages/track_bar_page.dart';
import 'package:example/pages/progress_bar_page.dart';
import 'package:example/pages/rich_text_box_page.dart';
import 'package:example/pages/tool_tip_page.dart';
import 'package:example/pages/error_provider_page.dart';
import 'package:example/pages/scrollable_control_page.dart';
import 'package:example/pages/typography_page.dart';
import 'package:example/pages/kbd_page.dart';
import 'package:example/pages/separator_page.dart';
import 'package:example/pages/tag_page.dart';
import 'package:example/pages/field_page.dart';
import 'package:example/pages/marker_page.dart';
import 'package:example/pages/button_group_page.dart';
import 'package:example/pages/input_group_page.dart';
import 'package:example/pages/textarea_page.dart';
import 'package:example/pages/toggle_page.dart';
import 'package:example/pages/toggle_group_page.dart';
import 'package:example/pages/toggle_switch_page.dart';
import 'package:example/pages/input_otp_page.dart';
import 'package:example/pages/group_box_page.dart';
import 'package:example/pages/tab_control_page.dart';
import 'package:example/pages/split_container_page.dart';
import 'package:example/pages/splitter_page.dart';
import 'package:example/pages/accordion_page.dart';
import 'package:example/pages/collapsible_page.dart';
import 'package:example/pages/sheet_page.dart';
import 'package:example/pages/side_panel_page.dart';
import 'package:example/pages/sidebar_page.dart';
import 'package:example/pages/carousel_page.dart';
import 'package:example/pages/popover_page.dart';
import 'package:example/pages/hover_card_page.dart';
import 'package:example/pages/drop_down_button_page.dart';
import 'package:example/pages/message_box_page.dart';
import 'package:example/pages/command_page.dart';
import 'package:example/pages/toast_page.dart';
import 'package:example/pages/direction_page.dart';
import 'package:example/pages/empty_page.dart';
import 'package:example/pages/check_row_page.dart';
import 'package:example/pages/search_input_page.dart';
import 'package:example/pages/inline_editor_page.dart';
import 'package:example/pages/chart_page.dart';
import 'package:example/pages/pagination_page.dart';
import 'package:example/pages/alert_page.dart';
import 'package:example/pages/attachment_page.dart';
import 'package:example/pages/avatar_page.dart';
import 'package:example/pages/breadcrumb_page.dart';
import 'package:example/pages/bubble_page.dart';
import 'package:example/pages/message_page.dart';
import 'package:example/pages/message_scroller_page.dart';
import 'package:example/pages/questionnaire_page.dart';
import 'package:example/pages/skeleton_page.dart';
import 'package:example/pages/spinner_page.dart';
import 'package:example/pages/quick_overview_page.dart';

final List<(String, Widget Function())> _pages = [
  ('label', () => const LabelPage()),
  ('input', () => const InputPage()),
  ('button', () => const ButtonPage()),
  ('check_box', () => const CheckBoxPage()),
  ('radio_button', () => const RadioButtonPage()),
  ('combo_box', () => const ComboBoxPage()),
  ('link_label', () => const LinkLabelPage()),
  ('masked_text_box', () => const MaskedTextBoxPage()),
  ('numeric_up_down', () => const NumericUpDownPage()),
  ('domain_up_down', () => const DomainUpDownPage()),
  ('field_row', () => const FieldRowPage()),
  ('icon_btn', () => const IconBtnPage()),
  ('selectable_card', () => const SelectableCardPage()),
  ('surface', () => const SurfacePage()),
  ('checked_list_box', () => const CheckedListBoxPage()),
  ('list_view', () => const ListViewPage()),
  ('list_item', () => const ListItemPage()),
  ('tree_view', () => const TreeViewPage()),
  ('data_grid_view', () => const DataGridViewPage()),
  ('property_grid', () => const PropertyGridPage()),
  ('menu_strip', () => const MenuStripPage()),
  ('tool_strip', () => const ToolStripPage()),
  ('toolbar_button', () => const ToolbarButtonPage()),
  ('context_menu_strip', () => const ContextMenuStripPage()),
  ('status_strip', () => const StatusStripPage()),
  ('date_time_picker', () => const DateTimePickerPage()),
  ('month_calendar', () => const MonthCalendarPage()),
  ('color_dialog', () => const ColorDialogPage()),
  ('dialog_box', () => const DialogBoxPage()),
  ('theme_designer', () => const ThemeDesignerPage()),
  ('binding_navigator', () => const BindingNavigatorPage()),
  ('scroll_bar', () => const ScrollBarPage()),
  ('track_bar', () => const TrackBarPage()),
  ('progress_bar', () => const ProgressBarPage()),
  ('rich_text_box', () => const RichTextBoxPage()),
  ('tool_tip', () => const ToolTipPage()),
  ('error_provider', () => const ErrorProviderPage()),
  ('scrollable_control', () => const ScrollableControlPage()),
  ('typography', () => const TypographyPage()),
  ('kbd', () => const KbdPage()),
  ('separator', () => const SeparatorPage()),
  ('tag', () => const TagPage()),
  ('field', () => const FieldPage()),
  ('marker', () => const MarkerPage()),
  ('button_group', () => const ButtonGroupPage()),
  ('input_group', () => const InputGroupPage()),
  ('textarea', () => const TextareaPage()),
  ('toggle', () => const TogglePage()),
  ('toggle_group', () => const ToggleGroupPage()),
  ('toggle_switch', () => const ToggleSwitchPage()),
  ('input_otp', () => const InputOtpPage()),
  ('group_box', () => const GroupBoxPage()),
  ('tab_control', () => const TabControlPage()),
  ('split_container', () => const SplitContainerPage()),
  ('splitter', () => const SplitterPage()),
  ('accordion', () => const AccordionPage()),
  ('collapsible', () => const CollapsiblePage()),
  ('sheet', () => const SheetPage()),
  ('side_panel', () => const SidePanelPage()),
  ('sidebar', () => const SidebarPage()),
  ('carousel', () => const CarouselPage()),
  ('popover', () => const PopoverPage()),
  ('hover_card', () => const HoverCardPage()),
  ('drop_down_button', () => const DropDownButtonPage()),
  ('message_box', () => const MessageBoxPage()),
  ('command', () => const CommandPage()),
  ('toast', () => const ToastPage()),
  ('direction', () => const DirectionPage()),
  ('empty', () => const EmptyPage()),
  ('check_row', () => const CheckRowPage()),
  ('search_input', () => const SearchInputPage()),
  ('inline_editor', () => const InlineEditorPage()),
  ('chart', () => const ChartPage()),
  ('pagination', () => const PaginationPage()),
  ('alert', () => const AlertPage()),
  ('attachment', () => const AttachmentPage()),
  ('avatar', () => const AvatarPage()),
  ('breadcrumb', () => const BreadcrumbPage()),
  ('bubble', () => const BubblePage()),
  ('message', () => const MessagePage()),
  ('message_scroller', () => const MessageScrollerPage()),
  ('questionnaire', () => const QuestionnairePage()),
  ('skeleton', () => const SkeletonPage()),
  ('spinner', () => const SpinnerPage()),
  ('quick_overview', () => const QuickOverviewPage()),
];

void main() {
  for (final (label, builder) in _pages) {
    testWidgets('smoke: $label', (tester) async {
      await tester.binding.setSurfaceSize(const Size(1280, 900));
      await tester.pumpWidget(MaterialApp(
        debugShowCheckedModeBanner: false,
        locale: const Locale('en'),
        supportedLocales: kSupportedLocales,
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        home: Material(type: MaterialType.transparency, child: builder()),
      ));
      await tester.pump(const Duration(milliseconds: 100));
      await tester.pump(const Duration(milliseconds: 100));
      expect(tester.takeException(), isNull, reason: '$label threw an exception');
      await tester.pumpWidget(const MaterialApp(home: SizedBox()));
      await tester.pump(const Duration(milliseconds: 50));
      expect(tester.takeException(), isNull, reason: '$label threw during teardown');
      await tester.binding.setSurfaceSize(null);
    });
  }
}